from pathlib import Path
from PIL import Image
import random

'''
function of the tool : crop the picture to a specific size

'''

# set the difficulty
'''
The size of picture shown to user will become
(1) easy : the same as original picture
(2) normal : 1/4 of original picture
(3) hard : 1/9 of original picture
(4) expert : 1/16 of original picture

'''
difficulty = ["easy", "normal", "hard", "expert"]
difficulty_ratio = {
    "easy" : 1.0,
    "normal" : 0.5,
    "hard" : 1/3,
    "expert" : 0.25
}

def cropPic(cache_id : str, dif : int, new_x = None, new_y = None) -> dict:     
    '''
    cache_id : str, generated by getPic
    dif: int, input of user
    new_x, new_y : int, the cropped center
    '''
    
    # get the target picture from cache file
    code_Path = Path(__file__).resolve().parent.parent
    pic_Path = code_Path / "cache" / Path(cache_id) / "originalPB.jpg"
    pic = Image.open(pic_Path)

    # define the level by user and LLM 
    if dif > 3:     # 防止LLM亂傳，先跑得動再說
        dif = dif % 4
    level_idx = dif
    level = difficulty[level_idx]

    # crop
    '''
    step 1. determine the size of new picture
    step 2. determine the middle of new picture (notice the range)
    step 3. crop
    step 4. save

    '''

    width, height = pic.size
    cropped_width = int(width * difficulty_ratio[level])
    cropped_height = int(height * difficulty_ratio[level])

    if (new_x == None) and (new_y == None):
        center_x = random.randint(cropped_width // 2,  width - cropped_width // 2)
        center_y = random.randint(cropped_height // 2,  height - cropped_height // 2)
    else:
        center_x = new_x
        center_y = new_y

    crp_left = center_x - cropped_width // 2
    crp_upper = center_y - cropped_height // 2
    crp_right = crp_left + cropped_width
    crp_lower = crp_upper + cropped_height
    cropped_pic = pic.crop((crp_left, crp_upper, crp_right, crp_lower))

    name_crp_pic = f"crop_pic_{level}.jpg"
    crp_pic_Path = code_Path / "cache" / Path(cache_id) / name_crp_pic
    cropped_pic.save(crp_pic_Path)

    resultProb = {
        "success" : True,
        "cache_id" : cache_id,
        "pb_pic_path" : str(crp_pic_Path),
        "difficulty" : dif,
        "crp_center_x" : center_x,
        "crp_center_y" : center_y
    }

    return resultProb

if __name__ == "__main__":
    print("輸入cache id:")
    cache_id = input()
    print("輸入難度數字(範圍為0到3):")
    dif = int(input())
    result = cropPic(cache_id, dif)
    print(result)
